fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    default_config: creation_form
    configs:
        creation_form:
            toolbar: basic
            config.removePlugins = 'elementspath,save,font';
            